### ISSUE TITLE
Cartridge shows 502 Error

### ISSUE THREAD

**Issue by tengyifei** [tengyifei/openshift-cartridge-nginx-hhvm#11]
Filed on behalf of `gerdamit [at] gmail.com`

```
==> nginx-hhvm/logs/nginx_error.log <==
2015/01/30 07:41:39 [error] 400040#0: *8 connect() to unix:/var/lib/openshift/{MY_APP_ID}/app-root/data/hhvm.sock failed (111: Connection refused) while connecting to upstream, client: XX.XX.XX.XX, server: {MY_HOST}.rhcloud.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/openshift/{MY_APP_ID}/app-root/data/hhvm.sock:", host: "{MY_HOST}.rhcloud.com"
```

```
Uncaught exception: 98 failed to bind to async server socket: /var/lib/openshift/{MY_APP_ID}/app-root/data/hhvm.sock: Address already in use
```

Looks like we need to either delete and recreate the socket upon start up, or use a random socket name.

**Comment by CoolSpring8** [comment]
Excuse me,It seemed like I got the same(or similar) error two days ago,too.(The cartridge,however,had been running well for a few days.)Might it be because of an update of OpenShift?Then we could try to work out a corresponding way to solve it.(However,I can't find anything about it on OpenShift Blog and it's just a guess)

**Comment by tengyifei** [comment]
Judging from the log, the connection between HHVM and Nginx conceivably went out of sync as both complaints not being able to reach each other. A tentative fix is pushed to the [`fix-file-socket`](https://github.com/tengyifei/openshift-cartridge-nginx-hhvm/tree/fix-file-socket) branch and is being tested for a few days before I merge it into master.

**Comment by tengyifei** [comment]
@CoolSpring8 ，测试服务器连着开了几天没啥问题。你用`fix-file-socket`创建一个cartridge试试吧！Cartridge URL: `https://cartreflect-claytondev.rhcloud.com/github/tengyifei/openshift-cartridge-nginx-hhvm?commit=fix-file-socket`

**Comment by CoolSpring8** [comment]
@tengyifei 好的，谢谢，我已经创建了一个app，目前运行正常。不知什么时候会将此修复放入master分支中呢？(我只是担心用此分支创建的Cartridge作为生产环境，以后没法直接升级……)

**Comment by tengyifei** [comment]
Good. I'm merging it right now.
