### ISSUE TITLE
Failure to launch ryanj/silex-base

### ISSUE THREAD

**Issue by ryanj** [tengyifei/openshift-cartridge-nginx-hhvm#18]
I often use my `silex-base` repo for testing PHP services on OpenShift.

However, I'm not sure if this cart understands how to handle this newer project layout (ryanj/silex-base).

The app failed to serve the default index page after launching from the CLI:

    rhc app create silexhhvm http://cartreflect-claytondev.rhcloud.com/github/tengyifei/openshift-cartridge-nginx-hhvm --from-code=http://github.com/ryanj/silex-base.git

And, had the same result from the web: https://openshift.redhat.com/app/console/application_type/custom?&cartridges[]=http://cartreflect-claytondev.rhcloud.com/github/tengyifei/openshift-cartridge-nginx-hhvm&initial_git_url=http://github.com/ryanj/silex-base&name=hhvm

PHP application maintainers should be able to use your cart as a dependency to launch their service.

**Comment by tengyifei** [comment]
Oh I understand it now. This cartridge has some built-in configurations which are automatically pulled when creating an application from scratch. They are located in `usr/template/config`. If an external code base is supplied, the essential configurations are missing.

**Comment by tengyifei** [comment]
With d45eba21ca76fdb2624c56debf160d4a2fd94c95, this *sort of* works, but there are a couple of discrepancies preventing it from serving the app:
1. Nginx is used, so it doesn't understand `.htaccess` files.
2. The default `www` root is located at the `www` folder of the code repository instead of the root directory.

There's really not much we can do here except to write notices in the README.

**Comment by ryanj** [comment]
That `silex-base` repo should reflect the newer-syle PHP project layouts that OpenShift expects.

Here is an example of a downloadable nodejs cart that will allow an initial_git_repo to be included:
https://github.com/ryanj/openshift-origin-cartridge-nodejs

PHP project maintainers should be able to use your cart with their initial git repo (via the `--from-code` flag):

    rhc app create noderestify https://raw.githubusercontent.com/ryanj/openshift-origin-cartridge-nodejs/master/metadata/manifest.yml --from-code=http://github.com/ryanj/restify-base.git

Here is the same thing using the web: https://openshift.redhat.com/app/console/application_type/custom?&cartridges[]=https://raw.githubusercontent.com/ryanj/openshift-origin-cartridge-nodejs/master/metadata/manifest.yml&initial_git_url=https://github.com/ryanj/restify-base.git&name=noderestify

**Comment by ryanj** [comment]
Getting this particular repo supported isn't very critical, but it's what I usually use to test PHP carts - to make sure that they're compatible with our newer expectations for PHP project layouts.

That `.htaccess` file might be optional.  I added that file to allow Apache to serve the static assets directly (whenever Apache is available).  If Apache isn't available, the app should be able to serve the static assets via PHP (see https://github.com/ryanj/silex-base/blob/master/app.php#L2)

I can re-enable this block of code if that helps - https://github.com/ryanj/silex-base/blob/master/app.php#L23

If nginx offers something similar to an `.htaccess` file, let me know.  I'd be happy to add it to my `silex-base` repo.

Thanks for looking into this issue! :)

**Comment by tengyifei** [comment]
Nginx configurations are centralized in one place - the configuration files, which were the missing ones I was talking about in the previous post. I'll write some auto detection logic to fit the new project layout.

**Comment by tengyifei** [comment]
With a24bce93aa911d2316738c72e303bd880cd22feb, it detects existence of `index.php` or `app.php` in the root directory. While this manages to get the PHP-side set up, static assets still cannot be served without a rewrite rule. The corresponding config file is `config/nginx.d/default.conf.erb`.

**Comment by tengyifei** [comment]
Closing for now because `silex-base` uses Apache configuration files, which are fundamentally different from those used by Nginx.
