### ISSUE TITLE
nginx can not include default.conf to nginx.conf

### ISSUE THREAD

**Issue by dangtanxp** [tengyifei/openshift-cartridge-nginx-hhvm#21]
At the end of file nginx.conf have include.conf but it File default.conf is dismissed when restart nginx.
I add everything into file default.conf but it not working.
I only copy code default.conf into file nginx.conf (at line include .../\*.conf;) and it work for me.

**Comment by tengyifei** [comment]
Can you provide the exact commands used to locate and edit `default.conf`? In order for your changes to take permanent effect they have to be committed into a git repository and pushed to the server.

This means that SSHing into the server and editing `usr/template/config/nginx.d/default.conf.erb` is not the way to go.

**Comment by dangtanxp** [comment]
/var/lib/openshift/<id>/nginx-hhvm/configuration/etc/nginx.conf

/var/lib/openshift/<id>/app-root/runtime/repo/config/nginx.d/default.conf 
I can write everything with "not rule" at this file but nginx don't noticed errors.
And if I config with rule, it don't work with my rule, it only work with nginx.conf.

/var/lib/openshift/<id>/nginx-hhvm/bin/control restart
It's OK without error, mywebsite run normal although have wrong config.
Even I restart repo at openshift website, it till run normal, I think nginx did not include default.conf.

**Comment by tengyifei** [comment]
You are right in that `default.conf` is renewed upon restart. Directly editing `default.conf` will not work, and neither is it encouraged. Please modify `default.conf.erb` inside your code repository and push the changes using git. To demonstrate how to do that:
```bash
# Create the app
rhc app create myapp http://cartreflect-claytondev.rhcloud.com/github/tengyifei/openshift-cartridge-nginx-hhvm
# Enter the app code repository
cd myapp
# Modify the config file using an editor of your choice
vim config/nginx.d/default.conf.erb
# Commit and publish the changes
git commit -a -m "Update nginx config file"
git push origin master
```

**Comment by tengyifei** [comment]
It'd be great to have some feedback. Has this issue been resolved?

**Comment by dangtanxp** [comment]
All right, It's working. Can you upgrade nginx to last mainline (1.7.12) ?
