### ISSUE TITLE
504 Gateway Time-out, The server didn't respond in time.

### ISSUE THREAD

**Issue by ranib** [tengyifei/openshift-cartridge-nginx-hhvm#24]
Added this in config.ini.erb of hhvm.d to extend time-outs
```
; Connection timeouts
hhvm.server.connection_timeout_seconds = 600
hhvm.server.request_timeout_seconds = 600
```

I'm still getting these errors, any idea how I can resolve this?
```
[Thu May  7 19:57:12 2015] [hphp] [317533:7fe1e79ff700:47:000001] [] \nFatal error: entire web request took longer than 60 seconds and timed out
[Thu May  7 20:17:35 2015] [hphp] [470191:7fce9d9ff700:12:000001] [] Finished singleJitRequest 1
[Thu May  7 20:17:37 2015] [hphp] [470191:7fce9a9ff700:13:000001] [] Finished singleJitRequest 2
[Thu May  7 20:17:40 2015] [hphp] [470191:7fce9d9ff700:13:000001] [] Finished singleJitRequest 3
[Thu May  7 20:17:43 2015] [hphp] [470191:7fce9a9ff700:14:000001] [] Finished singleJitRequest 4
[Thu May  7 20:17:45 2015] [hphp] [470191:7fce9d9ff700:14:000001] [] Finished singleJitRequest 5
[Thu May  7 20:21:38 2015] [hphp] [470191:7fce9a9ff700:27:000001] [] SlowTimer [1142ms] at runtime/ext_mysql: slow query: INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (70, 'header_bg_image', '')
[Thu May  7 20:23:51 2015] [hphp] [470191:7fce9a9ff700:27:000002] [] \nFatal error: entire web request took longer than 300 seconds and timed out
```

**Comment by tengyifei** [comment]
Looks to me like the settings are not loaded by HHVM. Did you commit them inside your code repository and push to OpenShift as I suggested in #21 ?

**Comment by ranib** [comment]
Yes I did that is why 'connection timeout' got extended from 60s to 300s and date & time stamp started working after changing hhvm.log.header = false to 'true'. It seems like having problem connecting with mysql, but I may be wrong. BTW, I'm using scalable app and haproxy is working fine.

**Comment by tengyifei** [comment]
Based on your log, the mysql server is very slow: a single insertion query can take more than a second to execute. This problem most likely does not originate from HHVM nor this cartridge. Better to look for performance issues in mysql.

**Comment by ranib** [comment]
Correct, that is what I was thinking. can you point me to right direction?

**Comment by tengyifei** [comment]
As much as I'd like to help, there are simply too many factors involved
e.g. network issue (is the mysql server from the same datacenter?), sheer
amount of data, etc.
