### ISSUE TITLE
Update PHP Cli 5.3 to 5.4

### ISSUE THREAD

**Issue by reina3596** [tengyifei/openshift-cartridge-nginx-hhvm#25]
How I can update the PHP CLI version 5.3 to 5.4???

Thanks

**Comment by tengyifei** [comment]
If you are talking about the PHP installed on OpenShift systems, no there will not be an easy way to do that as OpenShift locks down pretty much everything. This cartridge installs HHVM not PHP onto OpenShift.

**Comment by reina3596** [comment]
I have a problem if I try to install Laravel becasue php 5.4 it is required.

In your cartridge...
php -v
PHP 5.3.3 (cli) (built: Oct 23 2014 06:58:46)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.1.4, Copyright (c) 2002-2012, by Derick Rethans

**Comment by tengyifei** [comment]
Either you can hack the installation script, replacing invocations of `php` to `hhvm` thus using the HHVM CLI, or you may use a method that does not involve the Laravel installer e.g. via Composer. This cartridge does not intend to replace the OpenShift system PH; it installs HHVM side-by-side.

**Comment by tengyifei** [comment]
Alternatively you may run this
```
alias php="LD_LIBRARY_PATH=~/nginx-hhvm/usr/bin ~/nginx-hhvm/usr/bin/hhvm"
```
To temporarily override PHP.
