### ISSUE TITLE
Please upgrade php version

### ISSUE THREAD

**Issue by tonythomas01** [tengyifei/openshift-cartridge-nginx-hhvm#29]
I see that the php version coming up installed with this catridge is php 5.3.x. Please upgrade to something new - minimum php 5.4

**Comment by tengyifei** [comment]
The `php` executable comes with OpenShift and cannot be replaced. You can, however, override it with the following alias:
```
alias php="LD_LIBRARY_PATH=~/nginx-hhvm/usr/bin ~/nginx-hhvm/usr/bin/hhvm"
```
