### ISSUE TITLE
Update nginx to 1.9.5 and hhvm to 3.9.0

### ISSUE THREAD

**Issue by afzalarsalan** [tengyifei/openshift-cartridge-nginx-hhvm#30]
Is there an update planned for this repo updating these two core components for this cartridge? If not how would I update these on my own with a forked repo?

**Comment by tengyifei** [comment]
The process consists of setting up an RHEL 6.4 environment, compiling HHVM and uploading the binaries. I may skip version 3.9.0 and go directly to 3.10 as it's giving me compilation issues.

**Comment by afzalarsalan** [comment]
Can you detail anything specific I would need to do past setting up a RHEL virtualbox and compiling into a binary? Any specific flags you use for compilation in this environment. Interested in debugging this for operation as I'm planning on using this for a openshift base.

**Comment by tengyifei** [comment]
I've updated HHVM. Nginx is to come soon.

**Comment by tjnapster555** [comment]
@tengyifei when new update will come ?

**Comment by tengyifei** [comment]
I'll get to this in a few days.

**Comment by Pr3s4ri0** [comment]
any news on update ?
