### ISSUE TITLE
CLIENT_RESULT: Application is either stopped or inaccessible CLIENT_RESULT?

### ISSUE THREAD

**Issue by vongalpha** [tengyifei/openshift-cartridge-nginx-hhvm#32]
Hi! 
When I update to version 3.8.1 
I checked bin/control start "CLIENT_MESSAGE: Version: 3.8.1"
And after I visit my site it's not worked. I don't know why? 
My site say 503 Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.2.15 (Red Hat) Server at ****.rhcloud.com Port 80
I has used command 
bin/control status
and I received messenge
CLIENT_RESULT: Application is either stopped or inaccessible
CLIENT_RESULT: curl:

I hope you can fix

**Comment by tengyifei** [comment]
Can you try the newest version i.e. HHVM 3.11.0, included in this repo?

**Comment by vongalpha** [comment]
thanks @tengyifei  for updated
