### ISSUE TITLE
Update HHVM NGINX Both

### ISSUE THREAD

**Issue by corientdev** [tengyifei/openshift-cartridge-nginx-hhvm#34]
Hi,

Thanks for this awesome thing.

Please Update HHVM & NGINX Both.

You can actually follow a proper release schedule for this cartridge that can be done easily as you can get the dates of next release of HHVM and NGINX Both.

**Comment by tengyifei** [comment]
Release schedule is a nice idea. Problem is sometimes I don't have an opportunity to compile them and package them, which can be quite time-consuming.
