### ISSUE TITLE
Permission errors when scaling app

### ISSUE THREAD

**Issue by pinodex** [tengyifei/openshift-cartridge-nginx-hhvm#9]
![screenshot from 2015-01-18 22 19 04](https://cloud.githubusercontent.com/assets/6258767/5792686/7c7bb6b6-9f60-11e4-9b1f-0fe0780926a3.png)

To reproduce the issue, create a new scalable app with this cartridge, and scale up the app. I have to do `chmod +x .openshift/action_hooks/deploy` on my local app repo and then push to temporarily fix the issue.

**Comment by tengyifei** [comment]
Fixed in f3b19a7f794f1f89d2d070bf2faa5cb4422b67d2. Could you please double check that?

**Comment by pinodex** [comment]
It's fixed now. :)
